[tool.poetry]
name = "distributed-pyspy"
version = "0.1.0"
description = "Profile the dask distributed scheduler with py-spy"
authors = ["Gabe Joseph <gjoseph92@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.1"
distributed = "^2021.3.0"
py-spy = "^0.3.4"
numpy = {version = "^1.20.2", optional = true}
pandas = {version = "^1.2.4", optional = true}
pytest = {version = "^6.2.3", optional = true}
pytest-docker-compose = {version = "^3.2.1", optional = true}
pytest-asyncio = {version = "^0.15.1", optional = true}

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.9.0"
isort = "^5.8.0"

[tool.poetry.extras]
docker = ["numpy", "pandas"]
test = ["numpy", "pandas", "pytest", "pytest-docker-compose", "pytest-asyncio"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
