[tool.poetry]
name = "distributed-pyspy"
version = "0.1.0"
description = "Profile the dask distributed scheduler with py-spy"
authors = ["Gabe Joseph <gjoseph92@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
distributed = "^2021.3.0"
py-spy = "^0.3.4"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.9.0"
isort = "^5.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
